// Liste de mots pour le jeux 
const listeMots = [
    'Cachalot',
     'Pétunia', 
     'Serviette', 
     'Harmonie', 
    'Tempête', 
    'Voyage', 
    'Liberté', 
    'Mystère', 
    'Étoile', 
    'Sérénité', 
    'Rivière', 
    'Château', 
    'Forêt', 'Amour', 
    'Rêve', 
    'Passion', 
    'Beauté', 
    'Sagesse', 
    'Courage', 
    'Espoir', 
    'Félicité', 
    'Légende', 
    'Destin','Aurore', 
    'Crépuscule', 
    'Montagne', 
    'Océan', 
    'Parfum', 
    'Silence', 
    'Symphonie', 
    'Énigme', 
    'Trésor', 
    'Poésie']
const listePhrase =["Pas de panique" ,
     "La vie, l’univers et le reste", 
     "Merci pour le poisson",
     "L'harmonie entre les hommes est précieuse.",
    "La tempête gronde au loin.",
    "Le voyage fut long et périlleux.",
    "La liberté est un droit fondamental.",
    "Le mystère enveloppe cette vieille maison.",
    "Une étoile brille dans la nuit.",
    "La sérénité règne dans ce jardin.",
    "La rivière serpente à travers la vallée.",
    "Le château se dresse sur la colline.",
    "La forêt est dense et mystérieuse.", "L'amour est le plus puissant des sentiments.",
    "Elle poursuivait son rêve avec détermination.",
    "Sa passion pour la musique était inégalée.",
    "La beauté de ce paysage est époustouflante.",
    "La sagesse vient avec l'expérience.",
    "Le courage de ces héros est admirable.",
    "L'espoir ne doit jamais s'éteindre.",
    "La félicité était palpable lors de leur réunion.",
    "Cette légende est transmise de génération en génération.",
    "Chacun forge son propre destin.","L'aurore annonce un nouveau jour.",
    "Le crépuscule apporte une douce mélancolie.",
    "La montagne se dresse majestueusement.",
    "L'océan murmure des secrets anciens.",
    "Le parfum des fleurs embaume l'air.",
    "Le silence de la nuit est apaisant.",
    "La symphonie résonne dans la salle.",
    "Cette énigme reste sans réponse.",
    "Le trésor était enfoui depuis des siècles.",
    "La poésie est l'expression de l'âme."]
    
 